from .extrai_codigos_internacao import extrai_codigos_internacao
from .ler_credenciais import ler_credenciais
from .chrome_options import get_chrome_options
from .interna_pacientes import interna_pacientes
from .logging import setup_logging
from .extrai_internados_sisreg import extrai_internados_sisreg
from .extrai_internados_ghosp import extrai_internados_ghosp
from .compara_internados import compara_internados
from .motivo_alta import motivo_alta
from .extrai_codigos_sisreg_alta import extrai_codigos_sisreg_alta
from .executa_alta import executa_alta
from .trata_restos import atualiza_restos
from .extrai_internacoes_duplicadas import extrai_internacoes_duplicadas
from .trata_duplicados import trata_duplicados
from .executa_alta import dar_alta
from .devolvidos import devolvidos
from .escaneia_pdf import pdf2csv
from .ghosp_nota import ghosp_nota
from .ghosp_cns import ghosp_cns